### PR TITLE
Manual lifetime management for Multi-DLL

### PR DESCRIPTION
**Pull request by avoroshilov**
Small set of fixes aiming to fix crashes and hangs when integrating Tracy into a separate DLL wrapper in a multi-DLL project.
The newly added `TRACY_MANUAL_LIFETIME` flags enable a submode of `TRACY_DELAYED_INIT` - in order to use it, both `TRACY_MANUAL_LIFETIME` and `TRACY_DELAYED_INIT` should be defined.

Changes:
* `StartupProfiler`/`ShutdownProfiler` functions are added when both flags defined, allowing to manually manage when profiler data is being created/destroyed.
* Profiler c-tor is split into two parts, `Profiler::SpawnWorkerThreads` contains the second part, allowing to first create profiler object and then call the `SpawnWorkerThreads` - thus removing the need for the atomic load.
* `ThreadExitHandler` deinitializes RP allocator.

### CODE REVIEW

**Comment by wolfpld** [comment]
I think `ThreadExitHandler` should also be added to the SysTrace threads (TracySysTrace.cpp:324, 458, 958, 1031).

**Comment by wolfpld** [comment]
Test compile for `TRACY_MANUAL_LIFETIME` should be added to CI configuration (at the end of `.github/workflows/gcc.yml`).

**Comment by wolfpld** [comment]
Some backlinks for reference:
https://bitbucket.org/wolfpld/tracy/issues/22/improve-tracy-in-multi-dll-projects
https://bitbucket.org/wolfpld/tracy/issues/25/tracy-may-cause-deadlock-s-on-exit-when

**Comment by mcleary** [comment]
That's pretty interesting. I've done a similar thing in my fork but this looks way better than the draft I have. The option to start/shutdown the profiler is really handy if you don't want to spawn threads that are not going to be used.

**Comment by avoroshilov** [comment]
@wolfpld thanks for recommendation, fixed. Also added thread exit handler to the SysTrace threads, but I haven't used them, so I will trust your judgement on that one :)

@mcleary glad you like it! That's an interesting question regarding the remaining messages, I haven't looked into that, but I would assume there could be some sort of a blocking syncwait at the shutdown/d-tor thet will ensure all the queues are empty, or something along those lines?

**Comment by avoroshilov** [comment]
@wolfpld all the CI builds for my MR so far were failing the
> MSVC / build (pull_request)
step, specifically, the errors I've noticed are:
```
Profiler GUI Debug:

Cannot open include file: 'capstone/capstone.h'
Cannot open include file: 'ft2build.h'
Cannot open include file: 'GLFW/glfw3.h'
```
but, I am not sure how these failures are related to my changes. Can you share some wisdom on how my changes could affect the package management (esp. in the Profiler GUI project) - and what should I do in order to fix these errors?

**Comment by wolfpld** [comment]
> Also added thread exit handler to the SysTrace threads, but I haven't used them, so I will trust your judgement on that one :)

You definitely should try the SysTrace functionality. Here are two videos showing what it enables:
https://www.youtube.com/watch?v=uJkrFgriuOo
https://www.youtube.com/watch?v=_hU7vw00MZ4

> Can you share some wisdom on how my changes could affect the package management (esp. in the Profiler GUI project) - and what should I do in order to fix these errors?

This is caused by https://github.com/microsoft/vcpkg/issues/12062, which has been fixed already, but still hasn't been deployed to GitHub's CI VMs.

**Pull request merged**
