### PR TITLE
Build fixes for Fedora

### PR DESCRIPTION
**Pull request by jimblandy**
These are a few minor build issues I ran into trying to build on Fedora 30.

### CODE REVIEW

**Comment by wolfpld** [comment]
Using `pkg-config` for `tbb` is problematic, as described in https://github.com/wolfpld/tracy/issues/48#issuecomment-645685669. See the last comment for a solution proposal.

**Comment by jimblandy** [comment]
Okay, this is now limited to changes to `profiler/build/unix/build.mk` that I think implement the combined idea in [#48 (comment)](https://github.com/wolfpld/tracy/issues/48#issuecomment-645685669).

**Comment by wolfpld** [comment]
Looks good. Can you add this also to other tools?

```
% git grep 'LIBS += -ltbb'
capture/build/unix/build.mk:    LIBS += -ltbb
csvexport/build/unix/build.mk:  LIBS += -ltbb
import-chrome/build/unix/build.mk:      LIBS += -ltbb
profiler/build/unix/build.mk:   LIBS += -ltbb
update/build/unix/build.mk:     LIBS += -ltbb
```

(Preferably in some common included makefile.)

**Comment by jimblandy** [comment]
There's more stuff that could be factored out, but those should be separate PRs.

**Pull request merged**
