### PR TITLE
Enable Tracy to work trivially via CMake FetchContent

### PR DESCRIPTION
**Pull request by tksuoran**
This PR makes Tracy trivial to use via CMake FetchContent by providing TracyClient CMake project and link target.

Usage in client CMake project:

```
FetchContent_Declare(
    tracy
    GIT_REPOSITORY https://github.com/tksuoran/tracy.git
    GIT_TAG        cmake-client
    #GIT_REPOSITORY https://github.com/wolfpld/tracy.git
    #GIT_TAG        master
    GIT_SHALLOW    TRUE
    GIT_PROGRESS   TRUE
)

FetchContent_MakeAvailable(tracy)
...
target_link_libraries(${_target} PUBLIC TracyClient)
```

TracyClient target provides include directories.

### CODE REVIEW

**Comment by wolfpld** [comment]
Please add usage instructions to the documentation.

**Comment by tksuoran** [comment]
I added something to `manual/tracy.tex`. I haven't tried to build the pdf though.

**Comment by wolfpld** [comment]
> I haven't tried to build the pdf though.

It will fail, because underscores are not escaped.

**Comment by wolfpld** [comment]
Merged manually.

**Pull request closed without merging**
