### PR TITLE
Add D3D11 Gpu Context/Zone

### PR DESCRIPTION
**Pull request by hugoam**
I've removed the dust on this old PR (https://bitbucket.org/Nukem9/tracy/commits/227d3e9d2b1518031af9fb0114abd37a3f7d4f7f)  and made it work with the current version of Tracy, because I needed to profile a D3D11 based application
Would you be interested in merging it in master ?
It's not completely clean yet (mostly I the macros are untested as I use the structures directly) so in any case don't press merge just yet :D But I'm curious to know if you're interested in upstreaming it

### CODE REVIEW

**Comment by wolfpld** [comment]
Yes, of course I'm interested in merging this.

There was also a second pull request for D3D11: https://bitbucket.org/wolfpld/tracy/pull-requests/34

Before this can be merged, the manual and AUTHORS list has to be updated.

**Comment by hugoam** [comment]
The second one you linked seems a bit simpler as it doesn't seem to use a disjoint query for each scope, but that could be potentially a problem maybe. Although the disjoint handling doesn't look perfect in the current PR either, and I'm not sure it would behave correctly in case of frequency change, I think it's hard to get perfectly right

**Comment by hugoam** [comment]
Do you know what would be the correct way to handle D3D11 disjoint event ? The current code just does not handle them at all. Looking at other profiling libraries, one way is to do a cpu/gpu resync at that point. Can we use the `calibrate` event for that ? Looking at some example code, I think that can only be done through a pipeline stall though, is that imaginable ?

**Comment by wolfpld** [comment]
> Do you know what would be the correct way to handle D3D11 disjoint event ?

I don't use D3D.

> Looking at other profiling libraries, one way is to do a cpu/gpu resync at that point. Can we use the GpuCalibration event for that ?

Not really. Calibration events are for recalibration, not for resyncing.

**Pull request closed without merging**
